### ISSUE TITLE
The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by ycjcl868** [Automattic/cli-table#128]
## Expected/Desired Behavior

Fill with either one:

1. Expected behavior for bugs
1. Desired behavior for improvements/enhancements

## Actual Behavior

error cli-table@0.3.2: The engine "node" is incompatible with this module. Expected version ">= 12.13.0". Got "10.19.0"

## Steps to Reproduce the Problem/Current behavior

1. Step 1
1. Step 2
1. Step 3

## (Optional) Additional notes and links

Any other relevant informations helping in debugging/implementing.

**Comment by chrean** [comment]
Hy @ycjcl868 ,

we have just released a hotfix to support Node 10+. That should fix your issue.

**Comment by ljharb** [comment]
This doesn't fix it, since v0.3.1 works on node v0.2.0 and greater. See #140.

**Comment by chrean** [comment]
@ljharb should be fixed via #140 , let me know if that's not the case.
