### ISSUE TITLE
Pushing "undefined" breaks in table.toString()

### ISSUE THREAD

**Issue by charltoons** [Automattic/cli-table#30]
When pushing using the array-per-row method, if one of the elements in the array is `undefined`, the table allows you to push it, but then will throw an error when `table.toString()` is called. The expected behavior that I would prefer is to just fill in the cell with space, but I guess a case could be made for throwing an error on the push. 

I've written a test to demonstrate it; I'll write a fix when I get some time.

```
 'test pushing undefined': function (){
    var table = new Table()
    table.push(['v0.1', 'Testing something cool']);
    table.push(['v0.2', undefined]);

    var expected = [
        '┌────┬──────────────────────┐'
      , '│v0.1│Testing something cool│'
      , '├────┼──────────────────────┤'
      , '│v0.2│                      │'
      , '└────┴──────────────────────┘'
    ];
    table.toString().should.eql(expected.join("\n"));
  }
```

which throws:

```
index.test.js test pushing undefined: TypeError: Cannot call method 'toString' of undefined
at /Users/user/Desktop/cli-table/lib/cli-table/index.js:183:27
at Array.forEach (native)
at generateRow (/Users/user/Desktop/cli-table/lib/cli-table/index.js:182:11)
at /Users/croberts1/Desktop/cli-table/lib/cli-table/index.js:276:16
at Table.forEach (native)
at Table.toString (/Users/user/Desktop/cli-table/lib/cli-table/index.js:259:10)
at Test.module.exports.test pushing undefined [as fn] (/Users/user/Desktop/cli-table/test/index.test.js:263:11)
at Test.runParallel (/Users/user/Desktop/cli-table/node_modules/expresso/bin/expresso:959:10)
at Test.run (/Users/user/Desktop/cli-table/node_modules/expresso/bin/expresso:924:18)
at next (/Users/user/Desktop/cli-table/node_modules/expresso/bin/expresso:867:22)


Failures: 1
```

**Comment by platbr** [comment]
same issue here

**Comment by platbr** [comment]
I fixed it changing in /Users/user/Desktop/cli-table/lib/cli-table/index.js:182

```
items.forEach(function (item, i) {
        var contents = item.toString().split("\n").reduce(function (memo, l) {
          memo.push(string(l, i));
          return memo;
        }, [])
        var height = contents.length;
        if (height > max_height) { max_height = height };

        cells.push({ contents: contents , height: height });
    });
```
with
```
items.forEach(function (item, i) {
        if (item == null){
            item = "";
        }
        var contents = item.toString().split("\n").reduce(function (memo, l) {
          memo.push(string(l, i));
          return memo;
        }, [])
        var height = contents.length;
        if (height > max_height) { max_height = height };

        cells.push({ contents: contents , height: height });
    });
```

**Comment by jamestalmage** [comment]
[cli-table2](https://github.com/jamestalmage/cli-table2) allows colspans.
(not with the api you mentioned, but colspans nonetheless)

**Comment by adadgio** [comment]
This issue shouldnt be closed, it still exists: `TypeError: Cannot read property 'toString' of null` because of undefined values
